/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as ApiPublicKashierWebhookRouteImport } from './routes/api/public/kashier-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKashierWebhookRoute = ApiPublicKashierWebhookRouteImport.update({
  id: '/api/public/kashier-webhook',
  path: '/api/public/kashier-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/': typeof TracksIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks': typeof TracksIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/tracks/': typeof TracksIndexRoute
  '/api/public/kashier-webhook': typeof ApiPublicKashierWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/oauth-callback'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/checkout'
    | '/dashboard'
    | '/welcome'
    | '/tracks/$slug'
    | '/tracks/'
    | '/api/public/kashier-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/oauth-callback'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/checkout'
    | '/dashboard'
    | '/welcome'
    | '/tracks/$slug'
    | '/tracks'
    | '/api/public/kashier-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/oauth-callback'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/welcome'
    | '/tracks/$slug'
    | '/tracks/'
    | '/api/public/kashier-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TracksSlugRoute: typeof TracksSlugRoute
  TracksIndexRoute: typeof TracksIndexRoute
  ApiPublicKashierWebhookRoute: typeof ApiPublicKashierWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kashier-webhook': {
      id: '/api/public/kashier-webhook'
      path: '/api/public/kashier-webhook'
      fullPath: '/api/public/kashier-webhook'
      preLoaderRoute: typeof ApiPublicKashierWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TracksSlugRoute: TracksSlugRoute,
  TracksIndexRoute: TracksIndexRoute,
  ApiPublicKashierWebhookRoute: ApiPublicKashierWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
